---
name: CI tools installation
description: Installs Rust and Python tools listed in a TOML file
author: Eir Nym

inputs:
  tools-file:
    description: Path to a TOML file containing tool versions
    required: false
    default: .github/ci-tools.toml
  section:
    description: TOML section to use (e.g. "tools", "tools.dev")
  rust-install-method:
    type: choice
    description: Method to install Rust tools
    required: false
    default: prefer-binstall
    options:
    - prefer-binstall
    - binstall
    - install
  python-install-method:
    type: choice
    description: Method to install Python packages
    required: false
    default: prefer-uv
    options:
    - prefer-uv
    - uv
    - pip
  force-install:
    type: boolean
    description: Force reinstall tool even if it is already installed
    required: false
    default: false
  dry-run:
    type: boolean
    description: Don't actually install anything. Command will be printed out
    required: false
    default: false
  log-level:
    type: choice
    description: Action logging level
    required: false
    default: info
    options:
    - debug
    - info
    - warn
    - error
runs:
  using: composite
  steps:
  - name: Install tools from tools file using cargo-binstall
    shell: bash
    run: |2

      case "$RUNNER_DEBUG$ACTIONS_STEP_DEBUG$ACTIONS_RUNNER_DEBUG" in
      *true*) setopt XTRACE; log_level=debug ;;
      *1*) set +x; log_level=debug ;;
      *) log_level=${{ inputs.log-level}} ;;
      esac

      case "${{ inputs.force-install }}" in
      true) force_install=true ;;
      *) unset force_install ;;
      esac

      case "${{ inputs.dry-run }}" in
      true) dry_run=true ;;
      *) unset dry_run ;;
      esac

      python "${{ github.action_path }}/entrypoint.py" \
        ${force_install:+--force-install} \
        ${dry_run:+--dry-run} \
        --rust-install-method ${{ inputs.rust-install-method }}
        --python-install-method ${{ inputs.python-install-method }}
        --log-level $log_level \
        "${{ inputs.tools-file }}" \
        "${{ inputs.section }}"
