---
name: CI tools installation
description: Installs Rust and Python tools listed in a TOML file
author: Eir Nym

inputs:
  tools-file:
    description: Path to a TOML file containing tool versions
    required: false
    default: .github/ci-tools.toml
  section:
    description: TOML section to use (e.g. "tools", "tools.dev")
  use-cargo-binstall:
    type: boolean
    description: Use `cargo binstall` to install Rust tools
    required: false
    default: true
  use-python-uv:
    type: boolean
    description: Use `uv` to install Python tools
    required: false
    default: true
  force-install:
    type: boolean
    description: Force reinstall tool even if it is already installed
    required: false
    default: false
  dry-run:
    type: boolean
    description: Don't actually install anything. Command will be printed out
    required: false
    default: false
  log-level:
    type: choice
    description: Action logging level
    required: false
    default: info
    options:
    - debug
    - info
    - warn
    - error
runs:
  using: composite
  steps:
  - name: Install tools from tools file using cargo-binstall
    shell: bash
    run: |
      log_level=${{ inputs.log-level}}
      if (( ${+RUNNER_DEBUG} )); { setopt XTRACE; log_level=debug;}

      case "${{ inputs.use-cargo-binstall }}" in
      true) use_cargo_binstall=true ;;
      *) unset use_cargo_binstall ;;
      esac

      case "${{ inputs.use-python-uv }}" in
      true) use_python_uv=true ;;
      *) unset use_python_uv ;;
      esac

      case "${{ inputs.force-install }}" in
      true) force_install=true ;;
      *) unset force_install ;;
      esac

      case "${{ inputs.dry-run }}" in
      true) dry_run=true ;;
      *) unset dry_run ;;
      esac

      # case "$RUNNER_DEBUG" in
      # true) log_level=debug ;;
      # *) log_level=${{ inputs.log-level}} ;;
      # esac

      if [ "$log_level" == "debug" ]; then
        echo "[DEBUG] log_level: $log_level"
        echo "[DEBUG] force_install: $force_install"
        echo "[DEBUG] use_python_uv: $use_python_uv"
        echo "[DEBUG] use_cargo_binstall: $use_cargo_binstall"
      fi

      python "${{ github.action_path }}/entrypoint.py" \
        ${force_install:+--force-install} \
        ${dry_run:+--dry-run} \
        ${use_cargo_binstall:+--use-cargo-binstall} \
        ${use_python_uv:+--use-python-uv} \
        --log-level $log_level \
        "${{ inputs.tools-file }}" \
        "${{ inputs.section }}"
