:toc: preamble
= Simple install action for CI tooling

CI action to quick install multiple development tools listed in a section of a TOML file.

== Simple example

.Example of `.github/ci-tools.toml`
[source, toml]
-----
[to-be-installed]
fd-find = { version = "10.3.0", source = "crate"}
pytest = { version = "9.0.2", source = "pypi"}

[other-section]
typos-cli = { version = "1.42.0", source = "crate" }
-----

.Example of usage in CI workflow
[source, yaml]
-----
- uses: cargo-bins/cargo-binstall@v1.16.6
- uses: eirnym-learn/install-ci-tooling@v1.0.2
    with:
    section: ci
-----

If one will request to install tools from `to-be-installed` section, only https://lib.rs/crates/fd-find[fd-find] and https://pypi.org/project/pytest[pytest] will be installed. https://lib.rs/crates/typos-cli[typos-cli] will not be installed as not requested.

== Configuration

[options=header]
|======
| variable | description | Default value | notes
// -------------------
| tools-file
| Path to a TOML file containing tool versions
| .github/ci-tools.toml
|
// -------------------
| section
| Section to use (e.g. "tools", "tools.dev")
|
|
// -------------------
| force-install
| Force reinstall tool even if already installed
| false
|
  At the moment supported only by Rust installers as they break if another version is installed.
  `pip` and `uv` just overwrite the installed packages.
// -------------------
| dry-run
| Any command will not be executed at all, just printed out.
| false
|
// -------------------
| log-level
| Set logging level to a desired level.
| info
| At the moment only sets level for action itself.
// -------------------
| rust-install-method
| Use `cargo install` or `cargo binstall` to install a Rust tool
| preferred-binstall
|
// -------------------
| python-install-method
| Use `pip` or `uv` to install a Python package
| preferred-uv
|
// -------------------
|======

== IDE Integrations

link:ci-tools-schema.yaml[Json Schema] is public to use.

== FAQ

Can be found in link:FAQ.adoc[here].
